// 锟斤拷锟斤拷 Item definitions 锟斤拷锟斤拷

export type ItemRarity = "common" | "uncommon" | "rare" | "epic";

export type ItemCategory = "consumable" | "material" | "equipment";

export interface ItemDef {
  id: string;
  name: string;
  description: string;
  icon: string;           // emoji or image path (e.g. "/assets/ui/xx.png")
  category: ItemCategory;
  rarity: ItemRarity;
  stackable: boolean;
  maxStack: number;
  /** Effect applied when the player uses this item. Return true if consumed. */
  onUse?: (ctx: UseContext) => boolean;
  speedBonus?: number; // passive speed bonus for equipment
  equipSlot?: string;
  equipStats?: { atk?: number; def?: number; hp?: number; speed?: number };
}

export interface UseContext {
  heal: (amount: number) => void;
  boostAtk: (amount: number, duration: number) => void;
  boostDef: (amount: number, duration: number) => void;
  boostSpeed: (amount: number, duration: number) => void;
}

const RARITY_COLORS: Record<ItemRarity, string> = {
  common:   "#b0b0b0",
  uncommon: "#4caf50",
  rare:     "#2196f3",
  epic:     "#ab47bc",
};

export function rarityColor(r: ItemRarity): string {
  return RARITY_COLORS[r];
}

// 锟斤拷锟斤拷 Item registry 锟斤拷锟斤拷 烫烫烫？烫不烫

const ITEMS: Record<string, ItemDef> = {
  health_potion: {
    id: "health_potion",
    name: "生命药水",
    description: "恢复40点生命值。",
    icon: "/assets/ui/items/medium-health-potion.png",
    category: "consumable",
    rarity: "common",
    stackable: true,
    maxStack: 20,
    onUse: (ctx) => { ctx.heal(40); return true; },
  },
  greater_health_potion: {
    id: "greater_health_potion",
    name: "强效生命药水",
    description: "恢复70点生命值。",
    icon: "/assets/ui/items/large-health-potion.png",
    category: "consumable",
    rarity: "uncommon",
    stackable: true,
    maxStack: 10,
    onUse: (ctx) => { ctx.heal(70); return true; },
  },
  atk_scroll: {
    id: "atk_scroll",
    name: "攻击卷轴",
    description: "12秒内攻击力+6。",
    icon: "/assets/ui/items/Attack Scroll.png",
    category: "consumable",
    rarity: "rare",
    stackable: true,
    maxStack: 5,
    onUse: (ctx) => { ctx.boostAtk(6, 12); return true; },
  },
  def_scroll: {
    id: "def_scroll",
    name: "防御卷轴",
    description: "12秒内防御力+5。",
    icon: "/assets/ui/items/Defense Scroll.png",
    category: "consumable",
    rarity: "rare",
    stackable: true,
    maxStack: 5,
    onUse: (ctx) => { ctx.boostDef(5, 12); return true; },
  },
  slime_gel: {
    id: "slime_gel",
    name: "史莱姆凝胶",
    description: "史莱姆掉落的粘性物质，可用于制作。",
    icon: "/assets/ui/loot/slime gel.png",
    category: "material",
    rarity: "common",
    stackable: true,
    maxStack: 99,
  },
  bone_fragment: {
    id: "bone_fragment",
    name: "骨碎片",
    description: "骷髅掉落的碎片，可用于制作。",
    icon: "/assets/ui/loot/bone.png",
    category: "material",
    rarity: "common",
    stackable: true,
    maxStack: 99,
  },
  eagle_feather: {
    id: "eagle_feather",
    name: "鹰羽",
    description: "凶猛老鹰掉落的轻盈羽毛。",
    icon: "/assets/ui/loot/feather.png",
    category: "material",
    rarity: "uncommon",
    stackable: true,
    maxStack: 50,
  },
  orc_tusk: {
    id: "orc_tusk",
    name: "兽牙",
    description: "击败兽人获得的战利品。",
    icon: "/assets/ui/loot/metal2.png",
    category: "material",
    rarity: "uncommon",
    stackable: true,
    maxStack: 50,
  },
  bone_helmet: {
    id: "bone_helmet",
    name: "铁盔",
    description: "用铁材料制作的坚固头盔。防御+3，生命值+10。",
    icon: "/assets/ui/ArmourSets/helmet-common.png",
    category: "equipment",
    rarity: "uncommon",
    stackable: false,
    maxStack: 1,
    equipSlot: "helmet",
    equipStats: { def: 3, hp: 10 },
  },
  slime_chestplate: {
    id: "slime_chestplate",
    name: "史莱姆胸甲",
    description: "用史莱姆凝胶制作的粘稠胸甲。防御+5，生命值+15。",
    icon: "/assets/ui/ArmourSets/breastplate-common.png",
    category: "equipment",
    rarity: "uncommon",
    stackable: false,
    maxStack: 1,
    equipSlot: "chestplate",
    equipStats: { def: 5, hp: 15 },
  },
  bone_leggings: {
    id: "bone_leggings",
    name: "骨制护腿",
    description: "用骨头和兽牙强化的护腿。防御+4，生命值+8。",
    icon: "/assets/ui/ArmourSets/cuish-common.png",
    category: "equipment",
    rarity: "uncommon",
    stackable: false,
    maxStack: 1,
    equipSlot: "leggings",
    equipStats: { def: 4, hp: 8 },
  },
  eagle_boots: {
    id: "eagle_boots",
    name: "鹰羽靴",
    description: "用鹰羽制作的轻便靴子。防御+2，速度+20。",
    icon: "/assets/ui/ArmourSets/boot-common.png",
    category: "equipment",
    rarity: "uncommon",
    stackable: false,
    maxStack: 1,
    equipSlot: "boots",
    equipStats: { def: 2, speed: 30 },
    speedBonus: 30,
  },
  metal_helmet: {
    id: "metal_helmet",
    name: "铁盔",
    description: "用金属碎片锻造的坚固头盔。防御+5，生命值+15。",
    icon: "/assets/ui/ArmourSets/helmet-rare.png",
    category: "equipment",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    equipSlot: "helmet",
    equipStats: { def: 5, hp: 15 },
  },
  metal_chestplate: {
    id: "metal_chestplate",
    name: "铁甲",
    description: "用熔炼金属碎片打造的重型胸甲。防御+8，生命值+20。",
    icon: "/assets/ui/ArmourSets/breastplate-rare.png",
    category: "equipment",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    equipSlot: "chestplate",
    equipStats: { def: 8, hp: 20 },
  },
  metal_leggings: {
    id: "metal_leggings",
    name: "铁护腿",
    description: "用金属锻造的强化护腿。防御+6，生命值+12。",
    icon: "/assets/ui/ArmourSets/cuish-rare.png",
    category: "equipment",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    equipSlot: "leggings",
    equipStats: { def: 6, hp: 12 },
  },
  tusk_sword: {
    id: "tusk_sword",
    name: "兽牙剑",
    description: "用兽牙锻造的粗犷但强力的剑。攻击力+6。",
    icon: "/assets/ui/weapon/sword-common.png",
    category: "equipment",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    equipSlot: "weapon",
    equipStats: { atk: 6 },
  },
  iron_sword: {
    id: "iron_sword",
    name: "铁剑",
    description: "坚固的铁剑。攻击力+3。",
    icon: "/assets/ui/weapon/sword-common.png",
    category: "equipment",
    rarity: "common",
    stackable: false,
    maxStack: 1,
    equipSlot: "weapon",
    equipStats: { atk: 3 },
  },
  flame_blade: {
    id: "flame_blade",
    name: "炎之刃",
    description: "蕴含火焰之力的剑刃。攻击力+7，防御力+1。",
    icon: "/assets/ui/weapon/sword-epic.png",
    category: "equipment",
    rarity: "epic",
    stackable: false,
    maxStack: 1,
    equipSlot: "weapon",
    equipStats: { atk: 7, def: 1 },
  },
  dragon_slayer: {
    id: "dragon_slayer",
    name: "屠龙剑",
    description: "为屠龙而锻造的传奇剑刃。攻击力+12，生命值+20。",
    icon: "/assets/ui/weapon/sword-legendary.png",
    category: "equipment",
    rarity: "epic",
    stackable: false,
    maxStack: 1,
    equipSlot: "weapon",
    equipStats: { atk: 12, hp: 20 },
  },
  // --- Helmets ---
  iron_helmet: {
    id: "iron_helmet",
    name: "铁制头盔",
    description: "坚固的铁制头盔。防御+3，生命值+8。",
    icon: "/assets/ui/ArmourSets/helmet-common.png",
    category: "equipment",
    rarity: "common",
    stackable: false,
    maxStack: 1,
    equipSlot: "helmet",
    equipStats: { def: 3, hp: 8 },
  },
  steel_helmet: {
    id: "steel_helmet",
    name: "钢制头盔",
    description: "强化钢制头盔。防御+6，生命值+18。",
    icon: "/assets/ui/ArmourSets/helmet-rare.png",
    category: "equipment",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    equipSlot: "helmet",
    equipStats: { def: 6, hp: 18 },
  },
  dragon_helmet: {
    id: "dragon_helmet",
    name: "龙鳞头盔",
    description: "由龙鳞锻造而成。防御+10，生命值+30。",
    icon: "/assets/ui/ArmourSets/helmet-epic.png",
    category: "equipment",
    rarity: "epic",
    stackable: false,
    maxStack: 1,
    equipSlot: "helmet",
    equipStats: { def: 10, hp: 30 },
  },
  // --- Chestplates ---
  iron_chestplate: {
    id: "iron_chestplate",
    name: "铁制胸甲",
    description: "坚固的铁制胸甲。防御+5，生命值+15。",
    icon: "/assets/ui/ArmourSets/breastplate-common.png",
    category: "equipment",
    rarity: "common",
    stackable: false,
    maxStack: 1,
    equipSlot: "chestplate",
    equipStats: { def: 5, hp: 15 },
  },
  steel_chestplate: {
    id: "steel_chestplate",
    name: "钢制胸甲",
    description: "强化钢制胸甲。防御+9，生命值+25。",
    icon: "/assets/ui/ArmourSets/breastplate-rare.png",
    category: "equipment",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    equipSlot: "chestplate",
    equipStats: { def: 9, hp: 25 },
  },
  dragon_chestplate: {
    id: "dragon_chestplate",
    name: "龙鳞胸甲",
    description: "由龙鳞锻造而成。防御+14，生命值+40。",
    icon: "/assets/ui/ArmourSets/breastplate-epic.png",
    category: "equipment",
    rarity: "epic",
    stackable: false,
    maxStack: 1,
    equipSlot: "chestplate",
    equipStats: { def: 14, hp: 40 },
  },
  // --- Leggings ---
  iron_leggings: {
    id: "iron_leggings",
    name: "铁制护腿",
    description: "坚固的铁制护腿。防御+4，生命值+10。",
    icon: "/assets/ui/ArmourSets/cuish-common.png",
    category: "equipment",
    rarity: "common",
    stackable: false,
    maxStack: 1,
    equipSlot: "leggings",
    equipStats: { def: 4, hp: 10 },
  },
  steel_leggings: {
    id: "steel_leggings",
    name: "钢制护腿",
    description: "强化钢制护腿。防御+7，生命值+15。",
    icon: "/assets/ui/ArmourSets/cuish-rare.png",
    category: "equipment",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    equipSlot: "leggings",
    equipStats: { def: 7, hp: 15 },
  },
  dragon_leggings: {
    id: "dragon_leggings",
    name: "龙鳞护腿",
    description: "由龙鳞锻造而成。防御+11，生命值+25。",
    icon: "/assets/ui/ArmourSets/cuish-epic.png",
    category: "equipment",
    rarity: "epic",
    stackable: false,
    maxStack: 1,
    equipSlot: "leggings",
    equipStats: { def: 11, hp: 25 },
  },
  // --- Boots ---
  iron_boots: {
    id: "iron_boots",
    name: "铁靴",
    description: "厚重但防护力强的铁靴。防御+2，生命值+5。",
    icon: "/assets/ui/ArmourSets/boot-common.png",
    category: "equipment",
    rarity: "common",
    stackable: false,
    maxStack: 1,
    equipSlot: "boots",
    equipStats: { def: 2, hp: 5 },
  },
  steel_boots: {
    id: "steel_boots",
    name: "钢靴",
    description: "精钢靴。防御+5，生命值+10，速度+25。",
    icon: "/assets/ui/ArmourSets/boot-rare.png",
    category: "equipment",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    equipSlot: "boots",
    equipStats: { def: 5, hp: 10, speed: 25 },
    speedBonus: 25,
  },
  dragon_boots: {
    id: "dragon_boots",
    name: "龙鳞靴",
    description: "由龙鳞锻造而成。防御+8，生命值+18，速度+40。",
    icon: "/assets/ui/ArmourSets/boot-epic.png",
    category: "equipment",
    rarity: "epic",
    stackable: false,
    maxStack: 1,
    equipSlot: "boots",
    equipStats: { def: 8, hp: 18, speed: 40 },
    speedBonus: 40,
  },
  coin: {
      id: "coin",
      name: "金币",
    description: "闪闪发光的金币，可用于购买物品。",
      icon: "/assets/ui/loot/coin.png",
      category: "material",
      rarity: "common",
      stackable: true,
      maxStack: 999,
    },
    small_health_potion: {
      id: "small_health_potion",
      name: "小型生命药水",
    description: "恢复20点生命值。",
      icon: "/assets/ui/items/small-health-potion.png",
      category: "consumable",
      rarity: "common",
      stackable: true,
      maxStack: 30,
      onUse: (ctx) => { ctx.heal(20); return true; },
    },
    apple: {
      id: "apple",
      name: "苹果",
    description: "一个新鲜的苹果，恢复8点生命值。",
      icon: "/assets/ui/items/apple.png",
      category: "consumable",
      rarity: "common",
      stackable: true,
      maxStack: 30,
      onUse: (ctx) => { ctx.heal(8); return true; },
    },
    chicken: {
      id: "chicken",
      name: "烤鸡",
    description: "一顿丰盛的餐食，恢复50点生命值。",
      icon: "/assets/ui/items/chicken.png",
      category: "consumable",
      rarity: "uncommon",
      stackable: true,
      maxStack: 20,
      onUse: (ctx) => { ctx.heal(50); return true; },
    },
    coffee: {
      id: "coffee",
      name: "咖啡",
    description: "15秒内移动速度+30%。",
      icon: "/assets/ui/items/coffee.png",
      category: "consumable",
      rarity: "uncommon",
      stackable: true,
      maxStack: 10,
      onUse: (ctx) => { ctx.boostSpeed(30, 15); return true; },
    },
    // 锟絋锟絋锟絋 New materials 锟絋锟絋锟絋
    wood: {
      id: "wood",
      name: "木材",
    description: "一块木材，可用于制作。",
      icon: "/assets/ui/loot/wood.png",
      category: "material",
      rarity: "common",
      stackable: true,
      maxStack: 99,
    },
    metal_scrap: {
      id: "metal_scrap",
      name: "金属碎片",
    description: "金属碎片，可用于制作装备。",
      icon: "/assets/ui/loot/metal1.png",
      category: "material",
      rarity: "common",
      stackable: true,
      maxStack: 99,
    },
    gem: {
      id: "gem",
      name: "宝石",
    description: "珍贵的宝石，可用于制作高级装备。",
      icon: "/assets/ui/loot/gem.png",
      category: "material",
      rarity: "rare",
      stackable: true,
      maxStack: 50,
    },
    diamond: {
      id: "diamond",
      name: "钻石",
    description: "稀有的钻石。",
      icon: "/assets/ui/loot/diamond.png",
      category: "material",
      rarity: "epic",
      stackable: true,
      maxStack: 20,
    },
    undead_totem: {
      id: "undead_totem",
      name: "不死图腾",
    description: "似乎来自某人的世界……蕴含着神秘的力量。",
      icon: "/assets/ui/items/Undead Totem.png",
      category: "material",
      rarity: "rare",
      stackable: true,
      maxStack: 30,
    },
};

/** Enemy possible loot table (itemId, drop chance 0-1) */
export const ENEMY_LOOT_TABLE: Record<string, { itemId: string; chance: number }[]> = {
  slime:       [{ itemId: "slime_gel", chance: 0.6 }, { itemId: "coin", chance: 0.5 }, { itemId: "small_health_potion", chance: 0.2 }],
  red_slime:   [{ itemId: "slime_gel", chance: 0.7 }, { itemId: "coin", chance: 0.6 }, { itemId: "health_potion", chance: 0.3 }, { itemId: "gem", chance: 0.1 }, { itemId: "diamond", chance: 0.05 }],
  eagle:       [{ itemId: "eagle_feather", chance: 0.5 }, { itemId: "coin", chance: 0.4 }, { itemId: "atk_scroll", chance: 0.1 }],
  skeleton:    [{ itemId: "bone_fragment", chance: 0.6 }, { itemId: "coin", chance: 0.5 }, { itemId: "undead_totem", chance: 0.1 }, { itemId: "def_scroll", chance: 0.1 }],
  orc:         [{ itemId: "orc_tusk", chance: 0.7 }, { itemId: "coin", chance: 0.7 }, { itemId: "greater_health_potion", chance: 0.2 }, { itemId: "metal_scrap", chance: 0.3 },{ itemId: "diamond", chance: 0.1 }],
  goblin1:     [{ itemId: "metal_scrap", chance: 0.6 }, { itemId: "coin", chance: 0.5 }, { itemId: "wood", chance: 0.4 }, { itemId: "small_health_potion", chance: 0.15 }],
  goblin2:     [{ itemId: "metal_scrap", chance: 0.7 }, { itemId: "coin", chance: 0.6 }, { itemId: "bone_fragment", chance: 0.3 }, { itemId: "health_potion", chance: 0.2 }, { itemId: "gem", chance: 0.1 }],
  goblin3:     [{ itemId: "metal_scrap", chance: 0.9 },{ itemId: "eagle_feather", chance: 0.4 }, { itemId: "coin", chance: 0.5 }, { itemId: "coffee", chance: 0.15 }, { itemId: "gem", chance: 0.3 }],
  goblin4:     [{ itemId: "gem", chance: 0.7 }, { itemId: "coin", chance: 0.8 }, { itemId: "diamond", chance: 0.6 }, { itemId: "greater_health_potion", chance: 0.25 }, { itemId: "undead_totem", chance: 0.15 }],
};

export function isImageIcon(icon: string): boolean {
  return /\.(png|jpg|jpeg|gif|webp|svg)$/i.test(icon);
}

export function getItem(id: string): ItemDef | undefined {
  return ITEMS[id];
}

export function allItemIds(): string[] {
  return Object.keys(ITEMS);
}
