// ���� Item definitions ����

export type ItemRarity = "common" | "uncommon" | "rare" | "epic";

export type ItemCategory = "consumable" | "material" | "equipment";

export interface ItemDef {
  id: string;
  name: string;
  description: string;
  icon: string;           // emoji or image path (e.g. "/assets/ui/xx.png")
  category: ItemCategory;
  rarity: ItemRarity;
  stackable: boolean;
  maxStack: number;
  /** Effect applied when the player uses this item. Return true if consumed. */
  onUse?: (ctx: UseContext) => boolean;
  speedBonus?: number; // passive speed bonus for equipment
  equipSlot?: string;
  equipStats?: { atk?: number; def?: number; hp?: number; speed?: number };
}

export interface UseContext {
  heal: (amount: number) => void;
  boostAtk: (amount: number, duration: number) => void;
  boostDef: (amount: number, duration: number) => void;
  boostSpeed: (amount: number, duration: number) => void;
}

const RARITY_COLORS: Record<ItemRarity, string> = {
  common:   "#b0b0b0",
  uncommon: "#4caf50",
  rare:     "#2196f3",
  epic:     "#ab47bc",
};

export function rarityColor(r: ItemRarity): string {
  return RARITY_COLORS[r];
}

// ���� Item registry ����

const ITEMS: Record<string, ItemDef> = {
  health_potion: {
    id: "health_potion",
    name: "Health Potion",
    description: "Restores 30 HP.",
    icon: "/assets/ui/items/medium-health-potion.png",
    category: "consumable",
    rarity: "common",
    stackable: true,
    maxStack: 20,
    onUse: (ctx) => { ctx.heal(30); return true; },
  },
  greater_health_potion: {
    id: "greater_health_potion",
    name: "Greater Health Potion",
    description: "Restores 70 HP.",
    icon: "/assets/ui/items/large-health-potion.png",
    category: "consumable",
    rarity: "uncommon",
    stackable: true,
    maxStack: 10,
    onUse: (ctx) => { ctx.heal(70); return true; },
  },
  atk_scroll: {
    id: "atk_scroll",
    name: "Attack Scroll",
    description: "Boosts ATK by 8 for 15 seconds.",
    icon: "/assets/ui/items/Attack Scroll.png",
    category: "consumable",
    rarity: "rare",
    stackable: true,
    maxStack: 5,
    onUse: (ctx) => { ctx.boostAtk(8, 15); return true; },
  },
  def_scroll: {
    id: "def_scroll",
    name: "Defense Scroll",
    description: "Boosts DEF by 6 for 15 seconds.",
    icon: "/assets/ui/items/Defense Scroll.png",
    category: "consumable",
    rarity: "rare",
    stackable: true,
    maxStack: 5,
    onUse: (ctx) => { ctx.boostDef(6, 15); return true; },
  },
  slime_gel: {
    id: "slime_gel",
    name: "Slime Gel",
    description: "A sticky blob dropped by slimes. Can be sold.",
    icon: "/assets/ui/loot/slime gel.png",
    category: "material",
    rarity: "common",
    stackable: true,
    maxStack: 99,
  },
  bone_fragment: {
    id: "bone_fragment",
    name: "Bone Fragment",
    description: "Dropped by skeletons. Used in crafting.",
    icon: "/assets/ui/loot/bone.png",
    category: "material",
    rarity: "common",
    stackable: true,
    maxStack: 99,
  },
  eagle_feather: {
    id: "eagle_feather",
    name: "Eagle Feather",
    description: "A light feather from a fierce eagle.",
    icon: "/assets/ui/loot/feather.png",
    category: "material",
    rarity: "uncommon",
    stackable: true,
    maxStack: 50,
  },
  orc_tusk: {
    id: "orc_tusk",
    name: "Orc Tusk",
    description: "A trophy from a defeated orc.",
    icon: "/assets/ui/loot/metal2.png",
    category: "material",
    rarity: "uncommon",
    stackable: true,
    maxStack: 50,
  },
  bone_helmet: {
    id: "bone_helmet",
    name: "Bone Helmet",
    description: "A sturdy helmet crafted from bone fragments. DEF +3, HP +10.",
    icon: "/assets/ui/ArmourSets/helmet-common.png",
    category: "equipment",
    rarity: "uncommon",
    stackable: false,
    maxStack: 1,
    equipSlot: "helmet",
    equipStats: { def: 3, hp: 10 },
  },
  slime_chestplate: {
    id: "slime_chestplate",
    name: "Slime Chestplate",
    description: "A gooey chestplate made from slime gel. DEF +5, HP +15.",
    icon: "/assets/ui/ArmourSets/breastplate-common.png",
    category: "equipment",
    rarity: "uncommon",
    stackable: false,
    maxStack: 1,
    equipSlot: "chestplate",
    equipStats: { def: 5, hp: 15 },
  },
  bone_leggings: {
    id: "bone_leggings",
    name: "Bone Leggings",
    description: "Leg armor reinforced with bones and orc tusks. DEF +4, HP +8.",
    icon: "/assets/ui/ArmourSets/cuish-common.png",
    category: "equipment",
    rarity: "uncommon",
    stackable: false,
    maxStack: 1,
    equipSlot: "leggings",
    equipStats: { def: 4, hp: 8 },
  },
  eagle_boots: {
    id: "eagle_boots",
    name: "Eagle Boots",
    description: "Lightweight boots crafted from eagle feathers. DEF +2, SPD +20.",
    icon: "/assets/ui/ArmourSets/boot-common.png",
    category: "equipment",
    rarity: "uncommon",
    stackable: false,
    maxStack: 1,
    equipSlot: "boots",
    equipStats: { def: 2, speed: 30 },
    speedBonus: 30,
  },
  tusk_sword: {
    id: "tusk_sword",
    name: "Tusk Sword",
    description: "A crude but powerful sword forged from orc tusks. ATK +6.",
    icon: "/assets/ui/weapon/sword-common.png",
    category: "equipment",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    equipSlot: "weapon",
    equipStats: { atk: 6 },
  },
  iron_sword: {
    id: "iron_sword",
    name: "Iron Sword",
    description: "A sturdy iron blade. ATK +4.",
    icon: "/assets/ui/weapon/sword-common.png",
    category: "equipment",
    rarity: "common",
    stackable: false,
    maxStack: 1,
    equipSlot: "weapon",
    equipStats: { atk: 4 },
  },
  flame_blade: {
    id: "flame_blade",
    name: "Flame Blade",
    description: "A blade imbued with fire. ATK +10, DEF +2.",
    icon: "/assets/ui/weapon/sword-epic.png",
    category: "equipment",
    rarity: "epic",
    stackable: false,
    maxStack: 1,
    equipSlot: "weapon",
    equipStats: { atk: 10, def: 2 },
  },
  dragon_slayer: {
    id: "dragon_slayer",
    name: "Dragon Slayer",
    description: "A legendary blade forged to fell dragons. ATK +18, HP +30.",
    icon: "/assets/ui/weapon/sword-legendary.png",
    category: "equipment",
    rarity: "epic",
    stackable: false,
    maxStack: 1,
    equipSlot: "weapon",
    equipStats: { atk: 18, hp: 30 },
  },
  // --- Helmets ---
  iron_helmet: {
    id: "iron_helmet",
    name: "Iron Helmet",
    description: "A solid iron helmet. DEF +5, HP +15.",
    icon: "/assets/ui/ArmourSets/helmet-common.png",
    category: "equipment",
    rarity: "common",
    stackable: false,
    maxStack: 1,
    equipSlot: "helmet",
    equipStats: { def: 5, hp: 15 },
  },
  steel_helmet: {
    id: "steel_helmet",
    name: "Steel Helmet",
    description: "A reinforced steel helmet. DEF +8, HP +25.",
    icon: "/assets/ui/ArmourSets/helmet-rare.png",
    category: "equipment",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    equipSlot: "helmet",
    equipStats: { def: 8, hp: 25 },
  },
  dragon_helmet: {
    id: "dragon_helmet",
    name: "Dragon Helmet",
    description: "Forged from dragon scales. DEF +14, HP +40.",
    icon: "/assets/ui/ArmourSets/helmet-epic.png",
    category: "equipment",
    rarity: "epic",
    stackable: false,
    maxStack: 1,
    equipSlot: "helmet",
    equipStats: { def: 14, hp: 40 },
  },
  // --- Chestplates ---
  iron_chestplate: {
    id: "iron_chestplate",
    name: "Iron Chestplate",
    description: "A sturdy iron chestplate. DEF +7, HP +20.",
    icon: "/assets/ui/ArmourSets/breastplate-common.png",
    category: "equipment",
    rarity: "common",
    stackable: false,
    maxStack: 1,
    equipSlot: "chestplate",
    equipStats: { def: 7, hp: 20 },
  },
  steel_chestplate: {
    id: "steel_chestplate",
    name: "Steel Chestplate",
    description: "Reinforced steel plating. DEF +12, HP +30.",
    icon: "/assets/ui/ArmourSets/breastplate-rare.png",
    category: "equipment",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    equipSlot: "chestplate",
    equipStats: { def: 12, hp: 30 },
  },
  dragon_chestplate: {
    id: "dragon_chestplate",
    name: "Dragon Chestplate",
    description: "Forged from dragon scales. DEF +18, HP +50.",
    icon: "/assets/ui/ArmourSets/breastplate-epic.png",
    category: "equipment",
    rarity: "epic",
    stackable: false,
    maxStack: 1,
    equipSlot: "chestplate",
    equipStats: { def: 18, hp: 50 },
  },
  // --- Leggings ---
  iron_leggings: {
    id: "iron_leggings",
    name: "Iron Leggings",
    description: "Sturdy iron leg armor. DEF +6, HP +12.",
    icon: "/assets/ui/ArmourSets/cuish-common.png",
    category: "equipment",
    rarity: "common",
    stackable: false,
    maxStack: 1,
    equipSlot: "leggings",
    equipStats: { def: 6, hp: 12 },
  },
  steel_leggings: {
    id: "steel_leggings",
    name: "Steel Leggings",
    description: "Reinforced steel leg armor. DEF +10, HP +20.",
    icon: "/assets/ui/ArmourSets/cuish-rare.png",
    category: "equipment",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    equipSlot: "leggings",
    equipStats: { def: 10, hp: 20 },
  },
  dragon_leggings: {
    id: "dragon_leggings",
    name: "Dragon Leggings",
    description: "Forged from dragon scales. DEF +16, HP +35.",
    icon: "/assets/ui/ArmourSets/cuish-epic.png",
    category: "equipment",
    rarity: "epic",
    stackable: false,
    maxStack: 1,
    equipSlot: "leggings",
    equipStats: { def: 16, hp: 35 },
  },
  // --- Boots ---
  iron_boots: {
    id: "iron_boots",
    name: "Iron Boots",
    description: "Heavy but protective iron boots. DEF +4, HP +8.",
    icon: "/assets/ui/ArmourSets/boot-common.png",
    category: "equipment",
    rarity: "common",
    stackable: false,
    maxStack: 1,
    equipSlot: "boots",
    equipStats: { def: 4, hp: 8 },
  },
  steel_boots: {
    id: "steel_boots",
    name: "Steel Boots",
    description: "Reinforced steel boots. DEF +7, HP +15.",
    icon: "/assets/ui/ArmourSets/boot-rare.png",
    category: "equipment",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    equipSlot: "boots",
    equipStats: { def: 7, hp: 15, speed: 35 },
    speedBonus: 35,
  },
  dragon_boots: {
    id: "dragon_boots",
    name: "Dragon Boots",
    description: "Forged from dragon scales. DEF +12, HP +25.",
    icon: "/assets/ui/ArmourSets/boot-epic.png",
    category: "equipment",
    rarity: "epic",
    stackable: false,
    maxStack: 1,
    equipSlot: "boots",
    equipStats: { def: 12, hp: 25, speed: 50 },
    speedBonus: 50,
  },
  coin: {
      id: "coin",
      name: "Gold Coin",
      description: "Shiny gold coin. Used as currency.",
      icon: "/assets/ui/loot/coin.png",
      category: "material",
      rarity: "common",
      stackable: true,
      maxStack: 999,
    },
    small_health_potion: {
      id: "small_health_potion",
      name: "Small Health Potion",
      description: "Restores 15 HP.",
      icon: "/assets/ui/items/small-health-potion.png",
      category: "consumable",
      rarity: "common",
      stackable: true,
      maxStack: 30,
      onUse: (ctx) => { ctx.heal(15); return true; },
    },
    apple: {
      id: "apple",
      name: "Apple",
      description: "A fresh apple. Restores 10 HP.",
      icon: "/assets/ui/items/apple.png",
      category: "consumable",
      rarity: "common",
      stackable: true,
      maxStack: 30,
      onUse: (ctx) => { ctx.heal(10); return true; },
    },
    chicken: {
      id: "chicken",
      name: "Roast Chicken",
      description: "A hearty meal. Restores 50 HP.",
      icon: "/assets/ui/items/chicken.png",
      category: "consumable",
      rarity: "uncommon",
      stackable: true,
      maxStack: 20,
      onUse: (ctx) => { ctx.heal(50); return true; },
    },
    coffee: {
      id: "coffee",
      name: "Coffee",
      description: "Boosts movement speed by 40% for 20 seconds.",
      icon: "/assets/ui/items/coffee.png",
      category: "consumable",
      rarity: "uncommon",
      stackable: true,
      maxStack: 10,
      onUse: (ctx) => { ctx.boostSpeed(40, 20); return true; },
    },
    // �T�T�T New materials �T�T�T
    wood: {
      id: "wood",
      name: "Wood",
      description: "A piece of sturdy wood. Used in crafting.",
      icon: "/assets/ui/loot/wood.png",
      category: "material",
      rarity: "common",
      stackable: true,
      maxStack: 99,
    },
    metal_scrap: {
      id: "metal_scrap",
      name: "Metal Scrap",
      description: "Salvaged metal pieces. Used in crafting.",
      icon: "/assets/ui/loot/metal1.png",
      category: "material",
      rarity: "common",
      stackable: true,
      maxStack: 99,
    },
    gem: {
      id: "gem",
      name: "Gem",
      description: "A precious gemstone. Valuable and rare.",
      icon: "/assets/ui/loot/gem.png",
      category: "material",
      rarity: "rare",
      stackable: true,
      maxStack: 50,
    },
    diamond: {
      id: "diamond",
      name: "Diamond",
      description: "An extremely rare diamond.",
      icon: "/assets/ui/loot/diamond.png",
      category: "material",
      rarity: "epic",
      stackable: true,
      maxStack: 20,
    },
    undead_totem: {
      id: "undead_totem",
      name: "Undead Totem",
      description: "A dark totem dropped by undead creatures.",
      icon: "/assets/ui/items/Undead Totem.png",
      category: "material",
      rarity: "rare",
      stackable: true,
      maxStack: 30,
    },
};

/** Enemy possible loot table (itemId, drop chance 0-1) */
export const ENEMY_LOOT_TABLE: Record<string, { itemId: string; chance: number }[]> = {
  slime:       [{ itemId: "slime_gel", chance: 0.6 }, { itemId: "coin", chance: 0.5 }, { itemId: "small_health_potion", chance: 0.2 }],
  red_slime:   [{ itemId: "slime_gel", chance: 0.7 }, { itemId: "coin", chance: 0.6 }, { itemId: "health_potion", chance: 0.3 }],
  eagle:       [{ itemId: "eagle_feather", chance: 0.5 }, { itemId: "coin", chance: 0.4 }, { itemId: "atk_scroll", chance: 0.1 }],
  skeleton:    [{ itemId: "bone_fragment", chance: 0.6 }, { itemId: "coin", chance: 0.5 }, { itemId: "undead_totem", chance: 0.1 }, { itemId: "def_scroll", chance: 0.1 }],
  orc:         [{ itemId: "orc_tusk", chance: 0.5 }, { itemId: "coin", chance: 0.7 }, { itemId: "greater_health_potion", chance: 0.2 }, { itemId: "metal_scrap", chance: 0.3 }],
  goblin1:     [{ itemId: "metal_scrap", chance: 0.5 }, { itemId: "coin", chance: 0.5 }, { itemId: "wood", chance: 0.4 }, { itemId: "small_health_potion", chance: 0.15 }],
  goblin2:     [{ itemId: "metal_scrap", chance: 0.6 }, { itemId: "coin", chance: 0.6 }, { itemId: "bone_fragment", chance: 0.3 }, { itemId: "health_potion", chance: 0.2 }],
  goblin3:     [{ itemId: "eagle_feather", chance: 0.4 }, { itemId: "coin", chance: 0.5 }, { itemId: "coffee", chance: 0.15 }, { itemId: "gem", chance: 0.08 }],
  goblin4:     [{ itemId: "gem", chance: 0.3 }, { itemId: "coin", chance: 0.8 }, { itemId: "diamond", chance: 0.1 }, { itemId: "greater_health_potion", chance: 0.25 }, { itemId: "undead_totem", chance: 0.15 }],
};

export function isImageIcon(icon: string): boolean {
  return /\.(png|jpg|jpeg|gif|webp|svg)$/i.test(icon);
}

export function getItem(id: string): ItemDef | undefined {
  return ITEMS[id];
}

export function allItemIds(): string[] {
  return Object.keys(ITEMS);
}
